
platform :ios, '13.0'

use_frameworks!

target 'DuckUI_Example' do
  pod 'ReactiveKit'
  pod 'Layoutless'
  pod 'DuckUI', :path => '../'

  target 'DuckUI_Tests' do
    inherit! :search_paths

    
  end
end
